export * from './src/isConstructor'
export * from './src/isHex'
export * from './src/isHexOrUnicode'
export * from './src/isIterable'
export * from './src/isNumericString'
export * from './src/isObject'
export * from './src/isPrototype'
