export const response1 = [
  [
    'music',
    [
      'gig',
      'arrangement',
      'local scene',
      'underground venues',
      'bass',
      'sound quality',
      'bands',
      'live shows',
      'performance',
      'wireless equipment',
      'music festival',
      'music rehearsal',
      'gear',
      'album',
      'recording',
      'solo project',
      'music production',
      'band',
      'metal',
      'concert',
      'pink floyd',
      'listening to music',
      'interest in the album',
      'location of the studio',
      'visiting the recording studio',
      'computer drums',
      'listening to songs',
      'songs',
      'emotions',
      'jamming',
      'live performances',
      'music recommendations',
      'rock music',
      'guitar strings',
      'genre',
      'copenhell',
      'digidi',
      'microphones',
      'gear and equipment',
      'guitar',
      'singing',
      'band name',
      'vocals',
      'music recording',
      'vocal recording',
      'mixing',
      'lyrics',
      'rhythm',
      'editing',
      'solo band',
      'concert planning',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'training method',
      'music composition',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'audio plugin',
      'audio recording',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music composition',
      'sharing files',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'training method',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
    ],
  ],
  [
    'relationship',
    ['dating', 'breakup', 'meeting up', 'relationship', 'getting to know each other', 'love', 'relationship issues'],
  ],
  [
    'weekend plans',
    [
      'cancelling plans',
      'hangout invitation',
      'christmas plans',
      'next meeting',
      'plans',
      'hanging out',
      'games',
      'travel',
      'meeting',
      'drinking',
      'birthday celebration',
      'packing for the trip',
      'arriving at the destination',
      'sailing',
      'meeting tomorrow',
      'coming home',
      'plans for holidays',
    ],
  ],
  ['housing', ['sofa', 'mattress', 'sleeping arrangements', 'housing', 'rent', 'moving', 'storage']],
  [
    'food and drinks',
    ['pizza', 'beer', 'alcohol', 'food and drinks', 'food', 'groceries', 'drinks', 'eating', 'favorite food'],
  ],
  ['computer games', ['gaming', 'cs (counter-strike)', 'games', 'cs', 'playing games', 'cs:go']],
  ['transportation', ['metro', 'transportation', 'parking']],
  [
    'music equipment',
    [
      'wireless equipment',
      'gear',
      'microphones',
      'gear and equipment',
      'guitar',
      'vocal microphone',
      'direct box',
      'guitar rig',
      'installation',
      'guitar strings',
      'guitar equipment',
      'music equipment',
      'guitars',
    ],
  ],
  ['programming', ['debugging', 'compiler error', 'master project', 'json serializer/deserializer', 'coding']],
  ['mental health', ['self-doubt', 'feeling down', 'adhd diagnosis', 'support', 'optimal life', 'mental health']],
  [
    'music production',
    [
      'music production',
      'music recording',
      'mixing',
      'editing',
      'recording techniques',
      'audio recording',
      'album production',
      'song production',
      'remixing and remastering',
    ],
  ],
  [
    'musical learning',
    [
      'music theory',
      'hearing training',
      'instrument recommendations',
      'music composition',
      'counting music beats',
      'guitar techniques',
    ],
  ],
  [
    'personal life',
    [
      'family conflict',
      'stealing',
      'boredom',
      'activities',
      'health',
      'physical health',
      'relationships',
      'family',
      'personal struggles',
      'existence',
      'identity',
      'environment',
      'identity theft',
      'life coaching',
    ],
  ],
  ['social media', ['discord', 'google drive links', 'youtube']],
  ['education and career', ['job titles', 'teaching', 'job', 'online course', 'social offers']],
  ['personal struggles', ['pain', 'broken glasses', 'physical injury', 'car theft', 'debt', 'crime', 'death']],
  ['psychology', ['psychology', 'language', 'behavior']],
  ['art', ['sculpture', 'artwork']],
  ['religion and spirituality', ['religion', 'buddhism', 'meditation']],
  ['personal communication', ['phone call', 'texts', 'conversation', 'speaking style']],
  [
    'personal identity',
    [
      'age',
      'birthday',
      'age discrimination',
      'famous',
      'importance',
      'class',
      'skills',
      'fashion',
      'emoticons',
      'money',
      'trash',
    ],
  ],
  [
    'controversial topics',
    [
      '#metoo',
      'terrorism',
      'controversial jokes',
      'triggers',
      'news',
      'videos',
      'opiates',
      'narkoluder',
      'rip-benssteg',
    ],
  ],
  [
    'music preference',
    [
      'preference',
      'opener',
      'music recommendations',
      'interest in the album',
      'listening to music',
      'listening to songs',
      'music styles',
    ],
  ],
  [
    'music performance',
    ['live shows', 'performance', 'live performances', 'performances', 'concert', 'concert planning'],
  ],
  ['personal experiences', ['psychedelic experiences', 'experience']],
  [
    'personal relationships',
    [
      'love',
      'relationships',
      'relationship',
      'dating',
      'breakup',
      'meeting up',
      'getting to know each other',
      'relationship issues',
    ],
  ],
  [
    'personal health',
    ['physical health', 'health', 'vaccine', 'eye infection', 'physical injury', 'mental health', 'voice technique'],
  ],
  ['personal interests', ['interest in the album', 'hobby', 'interests']],
  ['personal skills', ['skills', 'ability', 'technique', 'training method']],
  ['personal feelings', ['emotions', 'self-doubt', 'feeling down']],
  [
    'personal activities',
    ['activities', 'hanging out', 'jamming', 'practicing', 'playing', 'making songs', 'coming home', 'eating'],
  ],
  [
    'personal planning',
    [
      'plans',
      'christmas plans',
      'next meeting',
      'birthday celebration',
      'packing for the trip',
      'arriving at the destination',
      'meeting tomorrow',
      'plans for holidays',
    ],
  ],
  [
    'personal belongings',
    [
      'glasses',
      'equipment',
      'gear',
      'guitar',
      'guitar rig',
      'installation',
      'guitar strings',
      'guitar equipment',
      'guitars',
    ],
  ],
  [
    'personal location',
    [
      'location',
      'local scene',
      'underground venues',
      'location of the studio',
      'visiting the recording studio',
      'address',
      'parking',
      'moving',
      'storage',
    ],
  ],
  ['personal transportation', ['transportation', 'metro', 'travel', 'parking']],
  ['personal finances', ['money', 'rent', 'debt', 'loans']],
  ['personal communication', ['phone call', 'texts', 'conversation', 'speaking style']],
  ['personal life events', ['birthdays', 'birthday', 'birthday celebration']],
  ['personal challenges', ['challenges', 'self-doubt', 'physical injury', 'car theft', 'debt', 'crime', 'death']],
  [
    'personal lifestyle',
    [
      'lifestyle',
      'sailing',
      'boredom',
      'activities',
      'health',
      'physical health',
      'relationships',
      'family',
      'personal struggles',
      'existence',
      'identity',
      'environment',
      'identity theft',
      'life coaching',
    ],
  ],
  ['personal learning', ['learning', 'teaching', 'online course', 'hearing training']],
  ['personal work', ['work', 'job titles', 'teaching', 'job', 'online course', 'social offers']],
  ['personal beliefs', ['beliefs', 'religion', 'buddhism', 'meditation']],
  ['personal art', ['art', 'sculpture', 'artwork']],
  [
    'personal technology',
    [
      'technology',
      'computer drums',
      'debugging',
      'compiler error',
      'master project',
      'json serializer/deserializer',
      'coding',
    ],
  ],
  [
    'personal food and drink',
    ['food and drinks', 'pizza', 'beer', 'alcohol', 'food', 'groceries', 'drinks', 'eating', 'favorite food'],
  ],
  [
    'personal computer games',
    ['computer games', 'gaming', 'cs (counter-strike)', 'games', 'cs', 'playing games', 'cs:go'],
  ],
  ['personal social media', ['social media', 'discord', 'google drive links', 'youtube']],
  ['writing', ['genesis', 'rumors', 'songwriting']],
  [
    'career',
    [
      'it careers',
      'career in it',
      'career options',
      'career choices',
      'work promotion',
      'job applications',
      'job search',
    ],
  ],
  [
    'depression',
    ['loneliness', 'substance use', 'paranoia', 'anxiety', 'emotional support', 'psychiatrist appointment'],
  ],
  ['video production', ['photoshop', 'quality of content', 'video editing', 'concert video', 'video rendering']],
  [
    'music',
    [
      'live performance',
      'technical requirements',
      'mastering',
      'audio editing',
      'song selection',
      'live singing',
      'pitch correction',
      'performance requirements',
      'band name ideas',
      'concert experience',
      'audio equipment',
      'basics of music',
      'riffs',
      'band names',
      'singers',
      'autotune',
      'band dynamics',
      'song composition',
      'progressive music',
      'cover art',
      'music lessons',
      'music genres',
      'studio recording',
      'genres',
      'metallica',
      'metal archives',
      'music industry',
      'music videos',
      'symphony orchestras',
      'sidechain compression',
    ],
  ],
  [
    'computer coding',
    [
      'software',
      'computer virus',
      'technical details',
      'backup solutions',
      'file sharing',
      'downloading',
      'virtual reality',
      'file sizes',
      'version numbers',
      'installing software',
      'computer programs',
      'it',
      'it supporter education',
      'support roles',
      'education options',
      'datalogi (computer science)',
      'ai',
      'technological literacy',
      'neural networks',
      'computer science',
      'machine learning',
      'technology',
      'quantum computing',
      'software engineering',
      'software development',
      'machine learning and data mining',
      'data science',
      'bachelor programs',
    ],
  ],
  [
    'life',
    [
      'destiny',
      'disabilities',
      'future plans',
      'asking for help',
      'sleep',
      'improvements',
      'date',
      'appearance',
      'regret',
      'hobbies',
      'hair loss',
      'eating habits',
      'family history',
      'having children',
      'holding children',
      'relationship preferences',
      'waiting for a response',
      'unpleasant experiences and memories',
      'personal experiences',
      'fear',
      'friendship',
      'name change',
      'dream',
      'cooking',
      'education',
      'appearance and style',
      'running',
      'tattoos',
      'internet',
      'therapy',
      'psychiatry',
      'psychotherapist',
      'cognitive therapy',
      'oatmeal',
      'quiz',
      'temperature',
      'pets',
      'universities',
      'career choices',
      'date mishap',
      'playing guitar',
      'being a non-smoker',
      'weird experiences at a brothel',
      'trauma',
      'music preferences',
      'dating experiences',
      'sharing personal information',
      'smiley meanings',
      'studying choices',
      'future aspirations',
      'iq and intelligence',
      'relationship decisions',
      'vocal processing',
      'new glasses',
      'world science festival',
      'organic food',
      'island vs mainland',
      'communication',
      'daily activities',
      'financial',
      'university',
      'engineering',
      'adhd',
      'spanish',
      'trimming',
      'metal music',
      'differences between universities',
      'jobs',
      'smoking',
      'positive changes',
    ],
  ],
  [
    'natural sciences',
    [
      'coronavirus',
      'polarization',
      'anatomy',
      'languages',
      'fractals',
      '3d program',
      'digital vs analog sound',
      'sleeping habits',
      'recommendations',
      'steven wilson',
      'social media',
      'attractiveness',
      'spanish language',
      'drugs',
      'swimming',
      'fractal art',
      'names',
      'science',
      'philosophy',
      'mars news',
      'elon musk',
      'package delivery',
      'copyright',
      'technology',
      'universities',
      'future technology',
      'artificial intelligence',
      'rockstars',
      'sørøver (pirates)',
      'strangelets',
      'quantum mechanics',
      'double slit experiment',
      'ct scanner',
      'dtu vs ku',
      'dtu',
    ],
  ],
  [
    'entertainment',
    [
      'outdoor activities',
      "queen's gambit",
      'netflix',
      'joe rogan',
      'video games',
      'comedy',
      'jokes',
      'naming children',
      'sexual innuendos',
      'exams',
      'hangover',
      'euphoria',
      'pladeselskaber',
      'outing',
      'gaffa tape',
      'reaper optimization',
      'guitar amp comparison',
      'endorsement',
      'merch shop',
      'facebook ads',
      'blocked on social media',
      'aliens',
      'purchase',
      'youtube channels',
      'promotion of music',
      'sex robots',
      'future technology',
      'pornhub',
      'sørøver (pirates)',
      'island vs mainland',
      'communication',
      'daily activities',
      'financial',
      'university',
      'strangelets',
      'engineering',
      'quantum mechanics',
      'double slit experiment',
      'adhd',
      'spanish',
      'trimming',
      'ct scanner',
      'metal music',
      'dtu vs ku',
      'software engineering',
      'differences between universities',
      'dtu',
      'jobs',
      'computer science and engineering',
      'machine learning and data mining',
      'data science',
      'bachelor programs',
      'software development',
      'smoking',
      'positive changes',
    ],
  ],
  ['medication', ['psychedelic substances', 'effects of psychedelics', 'buying drugs online', 'narcotics']],
  ['robotics', ['ai drones in warfare', 'neuralink']],
  [
    'music',
    [
      'singing vs writing music',
      'drum humanizer',
      'di boxes',
      'solos',
      'composing music',
      'reamping',
      'digitale amps',
      'counter strike',
      'guitar recording',
      'soloproject',
      'musical instruments',
      'auto-mastering software',
      'midi-transpose',
      'stemning af instrumenter',
      'effekter i musikproduktion',
      'voice leading',
      'instrument',
      'chorus',
      'guitar pro',
      'fortin nameless plugin',
      'free plugin',
      'gear and synths',
      'gin',
      'god lyd',
      'proteinpulver',
      'neurals bas-plugin',
      'organizing old ideas',
      'feedback on compositions',
      'sharing music and videos',
      'choir',
      'instrument learning',
      '3d printed guns',
      'amp modeling',
      'daily routines',
      'audio software industry',
      'demo',
      'keyboard',
      'guitar tone',
      'edderkopperock',
    ],
  ],
  [
    'education',
    [
      'it education',
      'mathematics education',
      'university education',
      'choice of education',
      'comparison of universities',
      'importance of practical experience',
      'career aspirations',
      'specialization',
      'learning resources',
      'programming languages',
      'job prospects',
      'courses',
      'self-study',
      'cs education',
      'school',
      'teknologisk udvikling',
      'humaniora uddannelse',
      'itu',
      'applied cs',
      'computronium',
      'python',
      'gymnasium',
      'university preferences',
    ],
  ],
  ['video games', ['pubg', 'apex legends', 'shooter games', 'battle royale games']],
  ['business', ['investment', 'luxury', 'entrepreneurship', 'selling items on dba', 'selling items']],
  ['tv shows', ['black mirror', 'rick and morty', 'bill gates documentary series', 'movies/documentaries']],
  [
    'job',
    [
      'job as software engineer',
      'job position',
      'job interview',
      'work',
      'job options',
      'job dissatisfaction',
      'job interviews',
      'salary negotiation',
      'work schedule',
      'being fired',
    ],
  ],
  [
    'data',
    ['gdpr', 'post-quantum-computer encryption', 'data breaches', 'data analysis', 'data ting', 'programmering'],
  ],
  ['gender', ['hair transplant', 'haircut', 'drag queens', 'gender experiences']],
  [
    'internet',
    [
      'collaboration with maja',
      'meeting over video call',
      'blogging',
      'influencer',
      'passwords',
      'gmail plugin',
      'ai chat bot',
      'dating apps',
      'the internet',
      'virtual reality (vr)',
    ],
  ],
  [
    'ethics',
    [
      'being offended',
      'feminism',
      'ethics and morality',
      'corruption in the public system',
      'supporting a problematic product',
      'nationalism',
      'honesty',
    ],
  ],
  [
    'math',
    [
      'mathematics',
      'equations',
      'unit circle',
      'trigonometry',
      'calculus',
      'value of pi',
      'math and computer science breakthroughs',
    ],
  ],
  ['science', ['intelligence', 'psychedelics', 'neuroscience', 'effects', 'astrophysics', 'naturvidenskab']],
  [
    'society',
    [
      'ubi (universal basic income)',
      'holland/netherlands',
      'mystery',
      'gender',
      'oysters',
      'astrology',
      'politics',
      'ethics',
      'multiculturalism',
      'cultural differences',
      'parenting',
      'literature',
      'personal anecdotes',
      'sexual experiences and preferences',
      'memory',
      'documentary',
      'harry potter',
      'flat earthers',
      'consciousness',
      'personality test',
      'intelligence test',
      'facebook page',
      'cleaning up social media',
      'autism',
      'exercise',
      'motivation',
      'reckless driving',
      'art',
      'it studies',
      'google drive',
      'revy',
      'cringe',
      'dancing',
      'musical',
      'diku-revy',
      "friend's acquaintance",
      'cleaning',
      'microplastics',
      'sex tech robots',
      'living in different cities',
      'drinking alcohol',
      'computer hardware',
      'studying',
      'sexual technology',
      'happiness',
      'sports',
      'painting',
      'public transport',
      'train travel',
      'work commute',
      'growing shrooms',
      'laughter',
      'iq testing',
      'relationship dynamics',
      'prestige of computer science',
      'train delays',
      'dsb (danish state railways)',
      'sleeping',
      'feelings',
      'aspergers',
      'mars',
      'ccpool',
      'stargazing',
      'train delay',
      'naked women',
      'prioritization',
      'blocked',
      'ideas',
      'kiss principle',
      'software development philosophies',
      'current events in france',
      'creativity',
      'theory',
      'student loans',
      'body image',
      "adele's weight loss",
      'projektarbejde',
      'learning styles',
      'medicine',
      'headphones',
      'organ playing',
      'concert tickets',
      'excitement',
      'rock concert',
      'fuzztival',
      'trip to herning',
      'course content',
      'learning process',
      'emil',
      'moon base',
      'efficiency',
      'video',
      'being tired',
      'packing gear',
      'attention to eating disorders',
      'organizing',
      'demonstration',
      'living conditions',
      'amplifiers',
      'digital technology',
      'plugin',
      'stemming',
      'algorithms',
      'buffer size',
      'single coils',
      'vst plugins',
      'quad cortex',
      'subjects',
      'personal growth',
      'self-improvement',
      'upbringing',
      'family dynamics',
      'spoiled behavior',
    ],
  ],
  ['self-reflection and personal growth', ['problem-solving', 'tiredness', 'routines', 'productivity']],
  ['hyper cubes', ['dimensionality', 'size comparison']],
  ['imaginary numbers', ['math homework', 'mathematical operations', 'complex numbers']],
  ['relativity theory', ['physics', 'electromagnetism', 'black holes', 'hawking radiation', 'dark matter']],
  ['monitors', ['subwoofer', 'camera technology']],
  [
    'mixing music',
    ['remaking songs', 'album recording', 'recording music', 'learning to growl', 'imitating thrash picking chugs'],
  ],
  [
    'it industry',
    ['neural plugin', 'hacker attack', 'software jobs', 'microchip engineers', 'automation', 'software career'],
  ],
  ['online education', ['podcasts', 'online teaching', 'online courses', 'udemy']],
  ['gender stereotypes', ['cultural influences', 'iq', 'iq tests']],
  [
    'job and career',
    [
      'academic requirements',
      'job opportunities',
      'choosing a career',
      'university options',
      'study options and career paths',
      'job prospects for computer science graduates',
    ],
  ],
  ['artificial meat', ['vegetarianism']],
  ['the simulation hypothesis', ['agi (artificial general intelligence)', 'google deep mind']],
  ['work environment', ['office vs. other work environments', 'working from home']],
  ['space exploration', ['solar eclipse']],
  ['tutorials', ['youtube tutorials']],
  ['travel plans', ['journey home', 'family trip', 'going to the store', 'train journey', 'travel to copenhagen']],
  ['open source', ['computersystems']],
  ['different universities', ['university programs']],
  ['prison system', ['lawyers', 'prostitution']],
  ['reading', ['book recommendation', 'books']],
  ['football', ['playing football', 'football match', 'feeling sore after playing football']],
  ['research', ['scholarships', 'strategy', 'stem education']],
  ['personal data', ['birthdate', 'name', 'weight', 'height', 'new phone setup']],
  ['music ai', ["google's text to speech", 'text-to-speech technology']],
  ['fitness center', ['fitness', 'gym', 'workout']],
  ['studying in aarhus', ['moving to aarhus', 'it byen in katrinebjerg']],
  ['socializing and meeting new people', ['finding a girlfriend', 'meeting old friend', 'meeting autistics']],
  ['routine', ['schedule', 'rigid routines']],
  ['phone', ['2 factor authentication']],
  ['well-being', ['simple health solutions']],
  ['personal interests', ['making money in music', 'planned activities']],
  [
    'future of work',
    [
      'automation and ai',
      'shortage of it professionals',
      'interest in computer science and it education',
      'shortage of it specialists',
    ],
  ],
  ['theater', ['dostojevskij event', 'dostojevskij teater']],
  ['racism', ['racial comments']],
  ['investments', ['money and salary']],
  ['karaoke', ['singing', 'concert']],
  ['vacation', ['travel', 'nature', 'vacation plans']],
  ['iq test', ['intelligence', 'intelligence tests']],
  ['computer', ['computersystems', 'coding skills', 'hardware projects']],
  [
    'studying computer science',
    [
      'admission process',
      'oversaturation of computer science field',
      'stem education',
      'misconceptions about html',
      'perception of computer science',
      'gpa',
      'supplementing',
    ],
  ],
  ['augmented reality', ['virtual reality', 'vr']],
  ['medical procedures', ['surgery', 'treatments']],
  ['lunch', ['food', 'meals']],
  ['team', ['colleagues', 'work teams', 'teamwork']],
  ['study group', ['studying', 'group studies']],
  ['buying a guitar', ['guitar features', 'harley benton guitars', 'electric vs. acoustic guitars']],
  ['history', ['historical events', 'historical figures']],
  ['creating games', ['game development', 'game design']],
  ['weekend work', ['work schedule', 'overtime']],
  ['literature', ['dostoevsky', 'orwell', 'dystopian literature']],
  [
    'programming',
    [
      'code review',
      'python programming',
      'craft of programming',
      'program development',
      'programming experience',
      'programming courses',
      'programming frameworks',
      'programming assignment',
      'mathematics in programming',
    ],
  ],
  [
    'dating',
    [
      'tinder',
      'tinder dating',
      'phone date',
      'date suggestion',
      'finding a date to meet',
      'phone dates',
      'relationship status',
    ],
  ],
  [
    'education',
    [
      'music education',
      'intro course',
      'formal lectures',
      'python course',
      'education system',
      'computer science education',
      'university experiences',
      'online learning resources',
      'academics',
    ],
  ],
  [
    'work',
    [
      'freedom in work',
      'working together',
      'new tasks',
      'quitting the course',
      'workload',
      'workplace experiences',
      'job security in health sector',
      'job prospects in health sector',
    ],
  ],
  [
    'music',
    [
      'music education',
      'possibly playing a concert',
      'drinking and listening to music',
      'festival',
      'lead guitar',
      'vocal styles in music',
      'music software',
      'playing in a band',
      'song feedback',
      'concept albums',
    ],
  ],
  [
    'health',
    [
      'sleep and routines',
      'exercise/health',
      'feeling unwell',
      "friend's health",
      'injuries',
      "doctor's appointment",
      'pain management',
      'doctors',
    ],
  ],
  [
    'software',
    [
      'graphics engine',
      'alphafold',
      'alphastar',
      'frontend development',
      'computation',
      'text editors',
      'coding ide',
      'ide preferences',
      'merge sort',
      'sextech project',
    ],
  ],
  [
    'social issues',
    [
      'asexuality',
      'demi sexuality',
      'age difference',
      'identity politics',
      'pride event',
      'abortion ban',
      'animal rights',
      'war in afghanistan',
    ],
  ],
  [
    'movies',
    [
      'tv show',
      'disney movies',
      'whiplash',
      'space jam',
      'lego movie',
      'pixar movies',
      'old disney movies',
      '70s space movie',
    ],
  ],
  [
    'university',
    [
      'lecturers',
      'meeting in aarhus',
      'classroom environment',
      'university and drug policy',
      'study',
      'course',
      'university experiences',
      'lectures',
      'friday bar',
    ],
  ],
  [
    'computer science',
    [
      'arrays',
      'big o notation',
      'text formatting',
      'binary',
      'octets',
      'hexadecimal',
      'command prompt',
      'syntax highlighting',
    ],
  ],
  ['music production', ['juce framework', 'audio software', 'badges', 'javascript']],
  ['nutrition', ['omega 3', 'vitamin d', 'sun exposure']],
]

export const response2 = [
  [
    'music',
    [
      'gig',
      'arrangement',
      'local scene',
      'underground venues',
      'bass',
      'sound quality',
      'bands',
      'live shows',
      'performance',
      'wireless equipment',
      'music festival',
      'music rehearsal',
      'gear',
      'album',
      'recording',
      'solo project',
      'music production',
      'band',
      'metal',
      'concert',
      'pink floyd',
      'listening to music',
      'interest in the album',
      'location of the studio',
      'visiting the recording studio',
      'computer drums',
      'listening to songs',
      'songs',
      'emotions',
      'jamming',
      'live performances',
      'music recommendations',
      'rock music',
      'guitar strings',
      'genre',
      'copenhell',
      'digidi',
      'microphones',
      'gear and equipment',
      'guitar',
      'singing',
      'band name',
      'vocals',
      'music recording',
      'vocal recording',
      'mixing',
      'lyrics',
      'rhythm',
      'editing',
      'solo band',
      'concert planning',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'training method',
      'music composition',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'audio plugin',
      'audio recording',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music composition',
      'sharing files',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'training method',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
      'music tone',
      'practice',
      'technique',
      'plugins',
      'biograf',
      'guitar playing',
      'equipment',
      'notes',
      'chords',
      'playing',
      'metal riffs',
      'guitar sound',
      'music composition',
      'sharing files',
      'guitar equipment',
      'distortion',
      'stereo guitars',
      'noise and stoj',
      'recording techniques',
      'challenges',
      'audio plugin',
      'audio recording',
      'compliments',
      'spotify',
      'beast song',
      'guitar solo',
      'quantize band',
      'justify rebellion',
    ],
  ],
  [
    'relationship',
    ['dating', 'breakup', 'meeting up', 'relationship', 'getting to know each other', 'love', 'relationship issues'],
  ],
  [
    'weekend plans',
    [
      'cancelling plans',
      'hangout invitation',
      'christmas plans',
      'next meeting',
      'plans',
      'hanging out',
      'games',
      'travel',
      'meeting',
      'drinking',
      'birthday celebration',
      'packing for the trip',
      'arriving at the destination',
      'sailing',
      'meeting tomorrow',
      'coming home',
      'plans for holidays',
    ],
  ],
  ['housing', ['sofa', 'mattress', 'sleeping arrangements', 'housing', 'rent', 'moving', 'storage']],
  [
    'food and drinks',
    ['pizza', 'beer', 'alcohol', 'food and drinks', 'food', 'groceries', 'drinks', 'eating', 'favorite food'],
  ],
  ['computer games', ['gaming', 'cs (counter-strike)', 'games', 'cs', 'playing games', 'cs:go']],
  ['transportation', ['metro', 'transportation', 'parking']],
  [
    'music equipment',
    [
      'wireless equipment',
      'gear',
      'microphones',
      'gear and equipment',
      'guitar',
      'vocal microphone',
      'direct box',
      'guitar rig',
      'installation',
      'guitar strings',
      'guitar equipment',
      'music equipment',
      'guitars',
    ],
  ],
  ['programming', ['debugging', 'compiler error', 'master project', 'json serializer/deserializer', 'coding']],
  ['mental health', ['self-doubt', 'feeling down', 'adhd diagnosis', 'support', 'optimal life', 'mental health']],
  [
    'music production',
    [
      'music production',
      'music recording',
      'mixing',
      'editing',
      'recording techniques',
      'audio recording',
      'album production',
      'song production',
      'remixing and remastering',
    ],
  ],
  [
    'musical learning',
    [
      'music theory',
      'hearing training',
      'instrument recommendations',
      'music composition',
      'counting music beats',
      'guitar techniques',
    ],
  ],
  [
    'personal life',
    [
      'family conflict',
      'stealing',
      'boredom',
      'activities',
      'health',
      'physical health',
      'relationships',
      'family',
      'personal struggles',
      'existence',
      'identity',
      'environment',
      'identity theft',
      'life coaching',
    ],
  ],
  ['social media', ['discord', 'google drive links', 'youtube']],
  ['education and career', ['job titles', 'teaching', 'job', 'online course', 'social offers']],
  ['personal struggles', ['pain', 'broken glasses', 'physical injury', 'car theft', 'debt', 'crime', 'death']],
  ['psychology', ['psychology', 'language', 'behavior']],
  ['art', ['sculpture', 'artwork']],
  ['religion and spirituality', ['religion', 'buddhism', 'meditation']],
  ['personal communication', ['phone call', 'texts', 'conversation', 'speaking style']],
  [
    'personal identity',
    [
      'age',
      'birthday',
      'age discrimination',
      'famous',
      'importance',
      'class',
      'skills',
      'fashion',
      'emoticons',
      'money',
      'trash',
    ],
  ],
  [
    'controversial topics',
    [
      '#metoo',
      'terrorism',
      'controversial jokes',
      'triggers',
      'news',
      'videos',
      'opiates',
      'narkoluder',
      'rip-benssteg',
    ],
  ],
  [
    'music preference',
    [
      'preference',
      'opener',
      'music recommendations',
      'interest in the album',
      'listening to music',
      'listening to songs',
      'music styles',
    ],
  ],
  [
    'music performance',
    ['live shows', 'performance', 'live performances', 'performances', 'concert', 'concert planning'],
  ],
  ['personal experiences', ['psychedelic experiences', 'experience']],
  [
    'personal relationships',
    [
      'love',
      'relationships',
      'relationship',
      'dating',
      'breakup',
      'meeting up',
      'getting to know each other',
      'relationship issues',
    ],
  ],
  [
    'personal health',
    ['physical health', 'health', 'vaccine', 'eye infection', 'physical injury', 'mental health', 'voice technique'],
  ],
  ['personal interests', ['interest in the album', 'hobby', 'interests']],
  ['personal skills', ['skills', 'ability', 'technique', 'training method']],
  ['personal feelings', ['emotions', 'self-doubt', 'feeling down']],
  [
    'personal activities',
    ['activities', 'hanging out', 'jamming', 'practicing', 'playing', 'making songs', 'coming home', 'eating'],
  ],
  [
    'personal planning',
    [
      'plans',
      'christmas plans',
      'next meeting',
      'birthday celebration',
      'packing for the trip',
      'arriving at the destination',
      'meeting tomorrow',
      'plans for holidays',
    ],
  ],
  [
    'personal belongings',
    [
      'glasses',
      'equipment',
      'gear',
      'guitar',
      'guitar rig',
      'installation',
      'guitar strings',
      'guitar equipment',
      'guitars',
    ],
  ],
  [
    'personal location',
    [
      'location',
      'local scene',
      'underground venues',
      'location of the studio',
      'visiting the recording studio',
      'address',
      'parking',
      'moving',
      'storage',
    ],
  ],
  ['personal transportation', ['transportation', 'metro', 'travel', 'parking']],
  ['personal finances', ['money', 'rent', 'debt', 'loans']],
  ['personal communication', ['phone call', 'texts', 'conversation', 'speaking style']],
  ['personal life events', ['birthdays', 'birthday', 'birthday celebration']],
  ['personal challenges', ['challenges', 'self-doubt', 'physical injury', 'car theft', 'debt', 'crime', 'death']],
  [
    'personal lifestyle',
    [
      'lifestyle',
      'sailing',
      'boredom',
      'activities',
      'health',
      'physical health',
      'relationships',
      'family',
      'personal struggles',
      'existence',
      'identity',
      'environment',
      'identity theft',
      'life coaching',
    ],
  ],
  ['personal learning', ['learning', 'teaching', 'online course', 'hearing training']],
  ['personal work', ['work', 'job titles', 'teaching', 'job', 'online course', 'social offers']],
  ['personal beliefs', ['beliefs', 'religion', 'buddhism', 'meditation']],
  ['personal art', ['art', 'sculpture', 'artwork']],
  [
    'personal technology',
    [
      'technology',
      'computer drums',
      'debugging',
      'compiler error',
      'master project',
      'json serializer/deserializer',
      'coding',
    ],
  ],
  [
    'personal food and drink',
    ['food and drinks', 'pizza', 'beer', 'alcohol', 'food', 'groceries', 'drinks', 'eating', 'favorite food'],
  ],
  [
    'personal computer games',
    ['computer games', 'gaming', 'cs (counter-strike)', 'games', 'cs', 'playing games', 'cs:go'],
  ],
  ['personal social media', ['social media', 'discord', 'google drive links', 'youtube']],
  ['writing', ['genesis', 'rumors', 'songwriting']],
  [
    'career',
    [
      'it careers',
      'career in it',
      'career options',
      'career choices',
      'work promotion',
      'job applications',
      'job search',
    ],
  ],
  [
    'depression',
    ['loneliness', 'substance use', 'paranoia', 'anxiety', 'emotional support', 'psychiatrist appointment'],
  ],
  ['video production', ['photoshop', 'quality of content', 'video editing', 'concert video', 'video rendering']],
  [
    'music',
    [
      'live performance',
      'technical requirements',
      'mastering',
      'audio editing',
      'song selection',
      'live singing',
      'pitch correction',
      'performance requirements',
      'band name ideas',
      'concert experience',
      'audio equipment',
      'basics of music',
      'riffs',
      'band names',
      'singers',
      'autotune',
      'band dynamics',
      'song composition',
      'progressive music',
      'cover art',
      'music lessons',
      'music genres',
      'studio recording',
      'genres',
      'metallica',
      'metal archives',
      'music industry',
      'music videos',
      'symphony orchestras',
      'sidechain compression',
    ],
  ],
  [
    'computer coding',
    [
      'software',
      'computer virus',
      'technical details',
      'backup solutions',
      'file sharing',
      'downloading',
      'virtual reality',
      'file sizes',
      'version numbers',
      'installing software',
      'computer programs',
      'it',
      'it supporter education',
      'support roles',
      'education options',
      'datalogi (computer science)',
      'ai',
      'technological literacy',
      'neural networks',
      'computer science',
      'machine learning',
      'technology',
      'quantum computing',
      'software engineering',
      'software development',
      'machine learning and data mining',
      'data science',
      'bachelor programs',
    ],
  ],
  [
    'life',
    [
      'destiny',
      'disabilities',
      'future plans',
      'asking for help',
      'sleep',
      'improvements',
      'date',
      'appearance',
      'regret',
      'hobbies',
      'hair loss',
      'eating habits',
      'family history',
      'having children',
      'holding children',
      'relationship preferences',
      'waiting for a response',
      'unpleasant experiences and memories',
      'personal experiences',
      'fear',
      'friendship',
      'name change',
      'dream',
      'cooking',
      'education',
      'appearance and style',
      'running',
      'tattoos',
      'internet',
      'therapy',
      'psychiatry',
      'psychotherapist',
      'cognitive therapy',
      'oatmeal',
      'quiz',
      'temperature',
      'pets',
      'universities',
      'career choices',
      'date mishap',
      'playing guitar',
      'being a non-smoker',
      'weird experiences at a brothel',
      'trauma',
      'music preferences',
      'dating experiences',
      'sharing personal information',
      'smiley meanings',
      'studying choices',
      'future aspirations',
      'iq and intelligence',
      'relationship decisions',
      'vocal processing',
      'new glasses',
      'world science festival',
      'organic food',
      'island vs mainland',
      'communication',
      'daily activities',
      'financial',
      'university',
      'engineering',
      'adhd',
      'spanish',
      'trimming',
      'metal music',
      'differences between universities',
      'jobs',
      'smoking',
      'positive changes',
    ],
  ],
  [
    'natural sciences',
    [
      'coronavirus',
      'polarization',
      'anatomy',
      'languages',
      'fractals',
      '3d program',
      'digital vs analog sound',
      'sleeping habits',
      'recommendations',
      'steven wilson',
      'social media',
      'attractiveness',
      'spanish language',
      'drugs',
      'swimming',
      'fractal art',
      'names',
      'science',
      'philosophy',
      'mars news',
      'elon musk',
      'package delivery',
      'copyright',
      'technology',
      'universities',
      'future technology',
      'artificial intelligence',
      'rockstars',
      'sørøver (pirates)',
      'strangelets',
      'quantum mechanics',
      'double slit experiment',
      'ct scanner',
      'dtu vs ku',
      'dtu',
    ],
  ],
  [
    'entertainment',
    [
      'outdoor activities',
      "queen's gambit",
      'netflix',
      'joe rogan',
      'video games',
      'comedy',
      'jokes',
      'naming children',
      'sexual innuendos',
      'exams',
      'hangover',
      'euphoria',
      'pladeselskaber',
      'outing',
      'gaffa tape',
      'reaper optimization',
      'guitar amp comparison',
      'endorsement',
      'merch shop',
      'facebook ads',
      'blocked on social media',
      'aliens',
      'purchase',
      'youtube channels',
      'promotion of music',
      'sex robots',
      'future technology',
      'pornhub',
      'sørøver (pirates)',
      'island vs mainland',
      'communication',
      'daily activities',
      'financial',
      'university',
      'strangelets',
      'engineering',
      'quantum mechanics',
      'double slit experiment',
      'adhd',
      'spanish',
      'trimming',
      'ct scanner',
      'metal music',
      'dtu vs ku',
      'software engineering',
      'differences between universities',
      'dtu',
      'jobs',
      'computer science and engineering',
      'machine learning and data mining',
      'data science',
      'bachelor programs',
      'software development',
      'smoking',
      'positive changes',
    ],
  ],
  ['medication', ['psychedelic substances', 'effects of psychedelics', 'buying drugs online', 'narcotics']],
  ['robotics', ['ai drones in warfare', 'neuralink']],
  [
    'music',
    [
      'singing vs writing music',
      'drum humanizer',
      'di boxes',
      'solos',
      'composing music',
      'reamping',
      'digitale amps',
      'counter strike',
      'guitar recording',
      'soloproject',
      'musical instruments',
      'auto-mastering software',
      'midi-transpose',
      'stemning af instrumenter',
      'effekter i musikproduktion',
      'voice leading',
      'instrument',
      'chorus',
      'guitar pro',
      'fortin nameless plugin',
      'free plugin',
      'gear and synths',
      'gin',
      'god lyd',
      'proteinpulver',
      'neurals bas-plugin',
      'organizing old ideas',
      'feedback on compositions',
      'sharing music and videos',
      'choir',
      'instrument learning',
      '3d printed guns',
      'amp modeling',
      'daily routines',
      'audio software industry',
      'demo',
      'keyboard',
      'guitar tone',
      'edderkopperock',
    ],
  ],
  [
    'education',
    [
      'it education',
      'mathematics education',
      'university education',
      'choice of education',
      'comparison of universities',
      'importance of practical experience',
      'career aspirations',
      'specialization',
      'learning resources',
      'programming languages',
      'job prospects',
      'courses',
      'self-study',
      'cs education',
      'school',
      'teknologisk udvikling',
      'humaniora uddannelse',
      'itu',
      'applied cs',
      'computronium',
      'python',
      'gymnasium',
      'university preferences',
    ],
  ],
  ['video games', ['pubg', 'apex legends', 'shooter games', 'battle royale games']],
  ['business', ['investment', 'luxury', 'entrepreneurship', 'selling items on dba', 'selling items']],
  ['tv shows', ['black mirror', 'rick and morty', 'bill gates documentary series', 'movies/documentaries']],
  [
    'job',
    [
      'job as software engineer',
      'job position',
      'job interview',
      'work',
      'job options',
      'job dissatisfaction',
      'job interviews',
      'salary negotiation',
      'work schedule',
      'being fired',
    ],
  ],
  [
    'data',
    ['gdpr', 'post-quantum-computer encryption', 'data breaches', 'data analysis', 'data ting', 'programmering'],
  ],
  ['gender', ['hair transplant', 'haircut', 'drag queens', 'gender experiences']],
  [
    'internet',
    [
      'collaboration with maja',
      'meeting over video call',
      'blogging',
      'influencer',
      'passwords',
      'gmail plugin',
      'ai chat bot',
      'dating apps',
      'the internet',
      'virtual reality (vr)',
    ],
  ],
  [
    'ethics',
    [
      'being offended',
      'feminism',
      'ethics and morality',
      'corruption in the public system',
      'supporting a problematic product',
      'nationalism',
      'honesty',
    ],
  ],
  [
    'math',
    [
      'mathematics',
      'equations',
      'unit circle',
      'trigonometry',
      'calculus',
      'value of pi',
      'math and computer science breakthroughs',
    ],
  ],
  ['science', ['intelligence', 'psychedelics', 'neuroscience', 'effects', 'astrophysics', 'naturvidenskab']],
  [
    'society',
    [
      'ubi (universal basic income)',
      'holland/netherlands',
      'mystery',
      'gender',
      'oysters',
      'astrology',
      'politics',
      'ethics',
      'multiculturalism',
      'cultural differences',
      'parenting',
      'literature',
      'personal anecdotes',
      'sexual experiences and preferences',
      'memory',
      'documentary',
      'harry potter',
      'flat earthers',
      'consciousness',
      'personality test',
      'intelligence test',
      'facebook page',
      'cleaning up social media',
      'autism',
      'exercise',
      'motivation',
      'reckless driving',
      'art',
      'it studies',
      'google drive',
      'revy',
      'cringe',
      'dancing',
      'musical',
      'diku-revy',
      "friend's acquaintance",
      'cleaning',
      'microplastics',
      'sex tech robots',
      'living in different cities',
      'drinking alcohol',
      'computer hardware',
      'studying',
      'sexual technology',
      'happiness',
      'sports',
      'painting',
      'public transport',
      'train travel',
      'work commute',
      'growing shrooms',
      'laughter',
      'iq testing',
      'relationship dynamics',
      'prestige of computer science',
      'train delays',
      'dsb (danish state railways)',
      'sleeping',
      'feelings',
      'aspergers',
      'mars',
      'ccpool',
      'stargazing',
      'train delay',
      'naked women',
      'prioritization',
      'blocked',
      'ideas',
      'kiss principle',
      'software development philosophies',
      'current events in france',
      'creativity',
      'theory',
      'student loans',
      'body image',
      "adele's weight loss",
      'projektarbejde',
      'learning styles',
      'medicine',
      'headphones',
      'organ playing',
      'concert tickets',
      'excitement',
      'rock concert',
      'fuzztival',
      'trip to herning',
      'course content',
      'learning process',
      'emil',
      'moon base',
      'efficiency',
      'video',
      'being tired',
      'packing gear',
      'attention to eating disorders',
      'organizing',
      'demonstration',
      'living conditions',
      'amplifiers',
      'digital technology',
      'plugin',
      'stemming',
      'algorithms',
      'buffer size',
      'single coils',
      'vst plugins',
      'quad cortex',
      'subjects',
      'personal growth',
      'self-improvement',
      'upbringing',
      'family dynamics',
      'spoiled behavior',
    ],
  ],
  ['self-reflection and personal growth', ['problem-solving', 'tiredness', 'routines', 'productivity']],
  ['hyper cubes', ['dimensionality', 'size comparison']],
  ['imaginary numbers', ['math homework', 'mathematical operations', 'complex numbers']],
  ['relativity theory', ['physics', 'electromagnetism', 'black holes', 'hawking radiation', 'dark matter']],
  ['monitors', ['subwoofer', 'camera technology']],
  [
    'mixing music',
    ['remaking songs', 'album recording', 'recording music', 'learning to growl', 'imitating thrash picking chugs'],
  ],
  [
    'it industry',
    ['neural plugin', 'hacker attack', 'software jobs', 'microchip engineers', 'automation', 'software career'],
  ],
  ['online education', ['podcasts', 'online teaching', 'online courses', 'udemy']],
  ['gender stereotypes', ['cultural influences', 'iq', 'iq tests']],
  [
    'job and career',
    [
      'academic requirements',
      'job opportunities',
      'choosing a career',
      'university options',
      'study options and career paths',
      'job prospects for computer science graduates',
    ],
  ],
  ['artificial meat', ['vegetarianism']],
  ['the simulation hypothesis', ['agi (artificial general intelligence)', 'google deep mind']],
  ['work environment', ['office vs. other work environments', 'working from home']],
  ['space exploration', ['solar eclipse']],
  ['tutorials', ['youtube tutorials']],
  ['travel plans', ['journey home', 'family trip', 'going to the store', 'train journey', 'travel to copenhagen']],
  ['open source', ['computersystems']],
  ['different universities', ['university programs']],
  ['prison system', ['lawyers', 'prostitution']],
  ['reading', ['book recommendation', 'books']],
  ['football', ['playing football', 'football match', 'feeling sore after playing football']],
  ['research', ['scholarships', 'strategy', 'stem education']],
  ['personal data', ['birthdate', 'name', 'weight', 'height', 'new phone setup']],
  ['music ai', ["google's text to speech", 'text-to-speech technology']],
  ['fitness center', ['fitness', 'gym', 'workout']],
  ['studying in aarhus', ['moving to aarhus', 'it byen in katrinebjerg']],
  ['socializing and meeting new people', ['finding a girlfriend', 'meeting old friend', 'meeting autistics']],
  ['routine', ['schedule', 'rigid routines']],
  ['phone', ['2 factor authentication']],
  ['well-being', ['simple health solutions']],
  ['personal interests', ['making money in music', 'planned activities']],
  [
    'future of work',
    [
      'automation and ai',
      'shortage of it professionals',
      'interest in computer science and it education',
      'shortage of it specialists',
    ],
  ],
  ['theater', ['dostojevskij event', 'dostojevskij teater']],
  ['racism', ['racial comments']],
  ['investments', ['money and salary']],
  ['karaoke', ['singing', 'concert']],
  ['vacation', ['travel', 'nature', 'vacation plans']],
  ['iq test', ['intelligence', 'intelligence tests']],
  ['computer', ['computersystems', 'coding skills', 'hardware projects']],
  [
    'studying computer science',
    [
      'admission process',
      'oversaturation of computer science field',
      'stem education',
      'misconceptions about html',
      'perception of computer science',
      'gpa',
      'supplementing',
    ],
  ],
  ['augmented reality', ['virtual reality', 'vr']],
  ['medical procedures', ['surgery', 'treatments']],
  ['lunch', ['food', 'meals']],
  ['team', ['colleagues', 'work teams', 'teamwork']],
  ['study group', ['studying', 'group studies']],
  ['buying a guitar', ['guitar features', 'harley benton guitars', 'electric vs. acoustic guitars']],
  ['history', ['historical events', 'historical figures']],
  ['creating games', ['game development', 'game design']],
  ['weekend work', ['work schedule', 'overtime']],
  ['literature', ['dostoevsky', 'orwell', 'dystopian literature']],
  [
    'programming',
    [
      'code review',
      'python programming',
      'craft of programming',
      'program development',
      'programming experience',
      'programming courses',
      'programming frameworks',
      'programming assignment',
      'mathematics in programming',
    ],
  ],
  [
    'dating',
    [
      'tinder',
      'tinder dating',
      'phone date',
      'date suggestion',
      'finding a date to meet',
      'phone dates',
      'relationship status',
    ],
  ],
  [
    'education',
    [
      'music education',
      'intro course',
      'formal lectures',
      'python course',
      'education system',
      'computer science education',
      'university experiences',
      'online learning resources',
      'academics',
    ],
  ],
  [
    'work',
    [
      'freedom in work',
      'working together',
      'new tasks',
      'quitting the course',
      'workload',
      'workplace experiences',
      'job security in health sector',
      'job prospects in health sector',
    ],
  ],
  [
    'music',
    [
      'music education',
      'possibly playing a concert',
      'drinking and listening to music',
      'festival',
      'lead guitar',
      'vocal styles in music',
      'music software',
      'playing in a band',
      'song feedback',
      'concept albums',
    ],
  ],
  [
    'health',
    [
      'sleep and routines',
      'exercise/health',
      'feeling unwell',
      "friend's health",
      'injuries',
      "doctor's appointment",
      'pain management',
      'doctors',
    ],
  ],
  [
    'software',
    [
      'graphics engine',
      'alphafold',
      'alphastar',
      'frontend development',
      'computation',
      'text editors',
      'coding ide',
      'ide preferences',
      'merge sort',
      'sextech project',
    ],
  ],
  [
    'social issues',
    [
      'asexuality',
      'demi sexuality',
      'age difference',
      'identity politics',
      'pride event',
      'abortion ban',
      'animal rights',
      'war in afghanistan',
    ],
  ],
  [
    'movies',
    [
      'tv show',
      'disney movies',
      'whiplash',
      'space jam',
      'lego movie',
      'pixar movies',
      'old disney movies',
      '70s space movie',
    ],
  ],
  [
    'university',
    [
      'lecturers',
      'meeting in aarhus',
      'classroom environment',
      'university and drug policy',
      'study',
      'course',
      'university experiences',
      'lectures',
      'friday bar',
    ],
  ],
  [
    'computer science',
    [
      'arrays',
      'big o notation',
      'text formatting',
      'binary',
      'octets',
      'hexadecimal',
      'command prompt',
      'syntax highlighting',
    ],
  ],
  ['music production', ['juce framework', 'audio software', 'badges', 'javascript']],
  ['nutrition', ['omega 3', 'vitamin d', 'sun exposure']],
]
