export * from './src/compareArray'
export * from './src/compareNumber'
export * from './src/compareNumberDescending'
export * from './src/compareNumeric'
export * from './src/compareNumericDescending'
export * from './src/compareString'
export * from './src/compareStringDescending'
